---
- name: Test authenticated Semaphore webhook
  hosts: local
  gather_facts: false

  tasks:
    - name: Display hello world
      ansible.builtin.debug:
        msg: "Hello world from Horse Plinko"

    - name: Display the remote webhook data
      ansible.builtin.debug:
        msg:
          - "Webhook message: {{ webhook_message | default('MISSING') }}"
          - "Request ID: {{ request_id | default('MISSING') }}"